//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitsNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrbitsNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amateur radio.
        /// </summary>
        internal static string amateurRadio {
            get {
                return ResourceManager.GetString("amateurRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth.
        /// </summary>
        internal static string azimuth {
            get {
                return ResourceManager.GetString("azimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_forth {
            get {
                object obj = ResourceManager.GetObject("back_forth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_forth_o {
            get {
                object obj = ResourceManager.GetObject("back_forth_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap batteries {
            get {
                object obj = ResourceManager.GetObject("batteries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap batteries_o {
            get {
                object obj = ResourceManager.GetObject("batteries_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREEZE-M R/B Breakup (2012-044C).
        /// </summary>
        internal static string breeze {
            get {
                return ResourceManager.GetString("breeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightest.
        /// </summary>
        internal static string brightest {
            get {
                return ResourceManager.GetString("brightest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btApply {
            get {
                return ResourceManager.GetString("btApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btClose {
            get {
                return ResourceManager.GetString("btClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string btLoad {
            get {
                return ResourceManager.GetString("btLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        internal static string btPlot {
            get {
                return ResourceManager.GetString("btPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string btSelect {
            get {
                return ResourceManager.GetString("btSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From celestrack.com.
        /// </summary>
        internal static string celestrack {
            get {
                return ResourceManager.GetString("celestrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication satellites.
        /// </summary>
        internal static string communication {
            get {
                return ResourceManager.GetString("communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conversation {
            get {
                object obj = ResourceManager.GetObject("conversation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conversation_o {
            get {
                object obj = ResourceManager.GetObject("conversation_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSMOS 2251 Debris.
        /// </summary>
        internal static string cosmos {
            get {
                return ResourceManager.GetString("cosmos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubeSats.
        /// </summary>
        internal static string cubes {
            get {
                return ResourceManager.GetString("cubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cycle {
            get {
                object obj = ResourceManager.GetObject("cycle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cycle_o {
            get {
                object obj = ResourceManager.GetObject("cycle_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaster monitoring.
        /// </summary>
        internal static string disaster {
            get {
                return ResourceManager.GetString("disaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth resources.
        /// </summary>
        internal static string earthResources {
            get {
                return ResourceManager.GetString("earthResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite-based augmentation system.
        /// </summary>
        internal static string egnos {
            get {
                return ResourceManager.GetString("egnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string elevation {
            get {
                return ResourceManager.GetString("elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string engineering {
            get {
                return ResourceManager.GetString("engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        internal static string experimental {
            get {
                return ResourceManager.GetString("experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FENGYUN 1C Debris.
        /// </summary>
        internal static string fengyun {
            get {
                return ResourceManager.GetString("fengyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLE files selection.
        /// </summary>
        internal static string filesSelection {
            get {
                return ResourceManager.GetString("filesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galileo.
        /// </summary>
        internal static string galileo {
            get {
                return ResourceManager.GetString("galileo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic.
        /// </summary>
        internal static string geodetic {
            get {
                return ResourceManager.GetString("geodetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geostationary.
        /// </summary>
        internal static string geostationary {
            get {
                return ResourceManager.GetString("geostationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalstar.
        /// </summary>
        internal static string globalstar {
            get {
                return ResourceManager.GetString("globalstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glonass operational.
        /// </summary>
        internal static string glonass {
            get {
                return ResourceManager.GetString("glonass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOES.
        /// </summary>
        internal static string goes {
            get {
                return ResourceManager.GetString("goes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorizont.
        /// </summary>
        internal static string gorizont {
            get {
                return ResourceManager.GetString("gorizont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site coordinates.
        /// </summary>
        internal static string gpCoordinates {
            get {
                return ResourceManager.GetString("gpCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Celestrack.com.
        /// </summary>
        internal static string gpFilesToLoad {
            get {
                return ResourceManager.GetString("gpFilesToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from local resources.
        /// </summary>
        internal static string gpLoadLocal {
            get {
                return ResourceManager.GetString("gpLoadLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS operational.
        /// </summary>
        internal static string gps {
            get {
                return ResourceManager.GetString("gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available TLEs.
        /// </summary>
        internal static string gpSelectTles {
            get {
                return ResourceManager.GetString("gpSelectTles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to load.
        /// </summary>
        internal static string gpSummarySelected {
            get {
                return ResourceManager.GetString("gpSummarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements to plot.
        /// </summary>
        internal static string gpSummaryTles {
            get {
                return ResourceManager.GetString("gpSummaryTles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time configuration.
        /// </summary>
        internal static string gpTime {
            get {
                return ResourceManager.GetString("gpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLE detail.
        /// </summary>
        internal static string gpTleDetails {
            get {
                return ResourceManager.GetString("gpTleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hospital_cross {
            get {
                object obj = ResourceManager.GetObject("hospital_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hospital_cross_o {
            get {
                object obj = ResourceManager.GetObject("hospital_cross_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAtomic_slashes {
            get {
                object obj = ResourceManager.GetObject("iconAtomic_slashes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAtomic_slashes_o {
            get {
                object obj = ResourceManager.GetObject("iconAtomic_slashes_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAuto_repair {
            get {
                object obj = ResourceManager.GetObject("iconAuto_repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconAuto_repair_o {
            get {
                object obj = ResourceManager.GetObject("iconAuto_repair_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBook {
            get {
                object obj = ResourceManager.GetObject("iconBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBook_o {
            get {
                object obj = ResourceManager.GetObject("iconBook_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBook2 {
            get {
                object obj = ResourceManager.GetObject("iconBook2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBook2_o {
            get {
                object obj = ResourceManager.GetObject("iconBook2_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBookOpen {
            get {
                object obj = ResourceManager.GetObject("iconBookOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconBookOpen_o {
            get {
                object obj = ResourceManager.GetObject("iconBookOpen_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconChemical_drop {
            get {
                object obj = ResourceManager.GetObject("IconChemical_drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconChemical_drop_o {
            get {
                object obj = ResourceManager.GetObject("IconChemical_drop_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCircuitry {
            get {
                object obj = ResourceManager.GetObject("iconCircuitry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCircuitry_o {
            get {
                object obj = ResourceManager.GetObject("iconCircuitry_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCompass {
            get {
                object obj = ResourceManager.GetObject("iconCompass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCompass_o {
            get {
                object obj = ResourceManager.GetObject("iconCompass_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCubes {
            get {
                object obj = ResourceManager.GetObject("iconCubes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCubes_o {
            get {
                object obj = ResourceManager.GetObject("iconCubes_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconForward_field {
            get {
                object obj = ResourceManager.GetObject("iconForward_field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconForward_field_o {
            get {
                object obj = ResourceManager.GetObject("iconForward_field_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMaterials_science {
            get {
                object obj = ResourceManager.GetObject("iconMaterials_science", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMaterials_science_o {
            get {
                object obj = ResourceManager.GetObject("iconMaterials_science_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMatraz {
            get {
                object obj = ResourceManager.GetObject("iconMatraz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMatraz_o {
            get {
                object obj = ResourceManager.GetObject("iconMatraz_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMesh_ball {
            get {
                object obj = ResourceManager.GetObject("iconMesh_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMesh_ball_o {
            get {
                object obj = ResourceManager.GetObject("iconMesh_ball_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOrbital {
            get {
                object obj = ResourceManager.GetObject("iconOrbital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconOrbital_o {
            get {
                object obj = ResourceManager.GetObject("iconOrbital_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconPointing {
            get {
                object obj = ResourceManager.GetObject("iconPointing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconPointing_o {
            get {
                object obj = ResourceManager.GetObject("iconPointing_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRadar_dish {
            get {
                object obj = ResourceManager.GetObject("IconRadar_dish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconRadar_dish_o {
            get {
                object obj = ResourceManager.GetObject("IconRadar_dish_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRadar_sweep {
            get {
                object obj = ResourceManager.GetObject("iconRadar_sweep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRadar_sweep_o {
            get {
                object obj = ResourceManager.GetObject("iconRadar_sweep_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRaining {
            get {
                object obj = ResourceManager.GetObject("iconRaining", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRaining_o {
            get {
                object obj = ResourceManager.GetObject("iconRaining_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRocket_flight {
            get {
                object obj = ResourceManager.GetObject("iconRocket_flight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconRocket_flight_o {
            get {
                object obj = ResourceManager.GetObject("iconRocket_flight_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconSatellite {
            get {
                object obj = ResourceManager.GetObject("iconSatellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconSatellite_o {
            get {
                object obj = ResourceManager.GetObject("iconSatellite_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconStar_swirl {
            get {
                object obj = ResourceManager.GetObject("iconStar_swirl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconStar_swirl_o {
            get {
                object obj = ResourceManager.GetObject("iconStar_swirl_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconStaryu {
            get {
                object obj = ResourceManager.GetObject("iconStaryu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconStaryu_o {
            get {
                object obj = ResourceManager.GetObject("iconStaryu_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconSteelwing_emblem {
            get {
                object obj = ResourceManager.GetObject("iconSteelwing_emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconSteelwing_emblem_o {
            get {
                object obj = ResourceManager.GetObject("iconSteelwing_emblem_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconTank {
            get {
                object obj = ResourceManager.GetObject("iconTank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconTank_o {
            get {
                object obj = ResourceManager.GetObject("iconTank_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconWorld {
            get {
                object obj = ResourceManager.GetObject("iconWorld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconWorld_o {
            get {
                object obj = ResourceManager.GetObject("iconWorld_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelsat.
        /// </summary>
        internal static string intelsat {
            get {
                return ResourceManager.GetString("intelsat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interdiction {
            get {
                object obj = ResourceManager.GetObject("interdiction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interdiction_o {
            get {
                object obj = ResourceManager.GetObject("interdiction_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iridium.
        /// </summary>
        internal static string iridiumComm {
            get {
                return ResourceManager.GetString("iridiumComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRIDIUM 33 Debris.
        /// </summary>
        internal static string iridiumSpecial {
            get {
                return ResourceManager.GetString("iridiumSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days launches.
        /// </summary>
        internal static string lastLaunches {
            get {
                return ResourceManager.GetString("lastLaunches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude [m].
        /// </summary>
        internal static string lblAltitude {
            get {
                return ResourceManager.GetString("lblAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to compute.
        /// </summary>
        internal static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude [º].
        /// </summary>
        internal static string lblLatitude {
            get {
                return ResourceManager.GetString("lblLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude [º].
        /// </summary>
        internal static string lblLongitude {
            get {
                return ResourceManager.GetString("lblLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step [s].
        /// </summary>
        internal static string lblStep {
            get {
                return ResourceManager.GetString("lblStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lob_arrow {
            get {
                object obj = ResourceManager.GetObject("lob_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lob_arrow_o {
            get {
                object obj = ResourceManager.GetObject("lob_arrow_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From local resources.
        /// </summary>
        internal static string localResources {
            get {
                return ResourceManager.GetString("localResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifying_glass {
            get {
                object obj = ResourceManager.GetObject("magnifying_glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifying_glass_o {
            get {
                object obj = ResourceManager.GetObject("magnifying_glass_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medal {
            get {
                object obj = ResourceManager.GetObject("medal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medal_o {
            get {
                object obj = ResourceManager.GetObject("medal_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous satellites.
        /// </summary>
        internal static string miscellaneous {
            get {
                return ResourceManager.GetString("miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous military.
        /// </summary>
        internal static string miscMilitary {
            get {
                return ResourceManager.GetString("miscMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molniya.
        /// </summary>
        internal static string molniya {
            get {
                return ResourceManager.GetString("molniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation satellites.
        /// </summary>
        internal static string navigation {
            get {
                return ResourceManager.GetString("navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy navigation satellite system (NNSS).
        /// </summary>
        internal static string navy {
            get {
                return ResourceManager.GetString("navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap night_sky {
            get {
                object obj = ResourceManager.GetObject("night_sky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap night_sky_o {
            get {
                object obj = ResourceManager.GetObject("night_sky_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOAA.
        /// </summary>
        internal static string noaa {
            get {
                return ResourceManager.GetString("noaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_book {
            get {
                object obj = ResourceManager.GetObject("open_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_book_o {
            get {
                object obj = ResourceManager.GetObject("open_book_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbcomm.
        /// </summary>
        internal static string orbcomm {
            get {
                return ResourceManager.GetString("orbcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OrbitsNet {
            get {
                object obj = ResourceManager.GetObject("OrbitsNet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OrbitsNetBlue {
            get {
                object obj = ResourceManager.GetObject("OrbitsNetBlue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string otherComm {
            get {
                return ResourceManager.GetString("otherComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string otherMisc {
            get {
                return ResourceManager.GetString("otherMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar.
        /// </summary>
        internal static string polar {
            get {
                return ResourceManager.GetString("polar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar calibration.
        /// </summary>
        internal static string radarCalibration {
            get {
                return ResourceManager.GetString("radarCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raduga.
        /// </summary>
        internal static string raduga {
            get {
                return ResourceManager.GetString("raduga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rapidshare_arrow {
            get {
                object obj = ResourceManager.GetObject("rapidshare_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rapidshare_arrow_o {
            get {
                object obj = ResourceManager.GetObject("rapidshare_arrow_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ringed_planet {
            get {
                object obj = ResourceManager.GetObject("ringed_planet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ringed_planet_o {
            get {
                object obj = ResourceManager.GetObject("ringed_planet_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian LEO navigation.
        /// </summary>
        internal static string russianLeo {
            get {
                return ResourceManager.GetString("russianLeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific satellites.
        /// </summary>
        internal static string scientific {
            get {
                return ResourceManager.GetString("scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and rescue (SARSAT).
        /// </summary>
        internal static string searchAndRescue {
            get {
                return ResourceManager.GetString("searchAndRescue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two line elements selection.
        /// </summary>
        internal static string selectTles {
            get {
                return ResourceManager.GetString("selectTles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space and Earth science.
        /// </summary>
        internal static string spaceAndEarth {
            get {
                return ResourceManager.GetString("spaceAndEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space stations.
        /// </summary>
        internal static string spaceStations {
            get {
                return ResourceManager.GetString("spaceStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special-interest satellites.
        /// </summary>
        internal static string specialInterest {
            get {
                return ResourceManager.GetString("specialInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt; load local TLE file &gt;.
        /// </summary>
        internal static string tbLocalFile {
            get {
                return ResourceManager.GetString("tbLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tornado {
            get {
                object obj = ResourceManager.GetObject("tornado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tornado_o {
            get {
                object obj = ResourceManager.GetObject("tornado_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartesian.
        /// </summary>
        internal static string tpCartesian {
            get {
                return ResourceManager.GetString("tpCartesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string tpConfig {
            get {
                return ResourceManager.GetString("tpConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selection.
        /// </summary>
        internal static string tpFilesSelection {
            get {
                return ResourceManager.GetString("tpFilesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string tpMap {
            get {
                return ResourceManager.GetString("tpMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar.
        /// </summary>
        internal static string tpPolar {
            get {
                return ResourceManager.GetString("tpPolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tle selection.
        /// </summary>
        internal static string tpTleSelection {
            get {
                return ResourceManager.GetString("tpTleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking and data relay satellite system (TDRSS).
        /// </summary>
        internal static string trackingAndRelay {
            get {
                return ResourceManager.GetString("trackingAndRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather and Earth resources satellites.
        /// </summary>
        internal static string weatherAndEarth {
            get {
                return ResourceManager.GetString("weatherAndEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap World_Standard_HiRes_grey {
            get {
                object obj = ResourceManager.GetObject("World_Standard_HiRes_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
